/* =====================================================================
   Central project / case-study data. One source of truth shared by the
   /projects hub, individual project pages and /before-and-after.
   RULES: real photographs only; omit any field that isn't verified
   (no invented suburbs, sizes, prices or customer names); a
   before/after pair must be two photographs of the SAME project.
   Dates come from the photo timestamps.
   ===================================================================== */

module.exports = [
  {
    slug: "front-garden-planter-transformation",
    title: "Front Garden Transformation — Raised Planter & New Lawn",
    categories: ["Retaining Walls", "Turf", "Garden Transformations"],
    summary: "A weed-covered mound on a new build turned into a raised sleeper planter with fresh turf, pebble borders and seasonal colour — finished in under two weeks.",
    challenge: "The front garden of this new build had been left as a bare, weed-covered mound — patchy soil, exposed irrigation line and no defined edge between the garden, driveway and footpath.",
    scope: [
      "Site clearing and weed removal",
      "Treated-pine sleeper planter wall with galvanised steel posts",
      "Quality topsoil supply, spread and levelling",
      "Instant turf supply and laying",
      "White pebble border and seasonal flower planting",
      "Existing magnolia retained and built around",
    ],
    approach: "The sleeper wall went in first to give the garden a clean, level frame, with galvanised posts set for long-term strength. Fresh topsoil brought the bed up to level before the turf was laid and rolled, and a white pebble border with seasonal flowers finished the front edge. The owner's established magnolia was kept and worked into the new lawn.",
    outcome: "A sharp, level front garden that lifts the whole street presence of the home — with a lawn the owners can actually use and a planter edge that will hold its line for years.",
    completed: "July 2026",
    hero: "proj-planter-after-1",
    gallery: [
      { img: "proj-planter-before-1", alt: "Before: weed-covered mound and patchy soil in the front garden of a new build" },
      { img: "proj-planter-before-2", alt: "Before: neglected garden bed with exposed irrigation line beside the driveway" },
      { img: "proj-planter-progress-1", alt: "During construction: treated-pine sleeper planter wall with fresh topsoil, ready for turf" },
      { img: "proj-planter-progress-2", alt: "During construction: sleeper wall built around the retained magnolia tree" },
      { img: "proj-planter-after-1", alt: "After: finished raised planter with fresh instant turf, white pebble border and seasonal flowers" },
      { img: "proj-planter-after-night", alt: "After at night: the finished planter bed with turf, pebbles and flowers beside the entry" },
    ],
    before: { img: "proj-planter-before-1", alt: "Before: weed-covered mound in front of the house" },
    after: { img: "proj-planter-after-1", alt: "After: raised sleeper planter with fresh turf, pebbles and flowers" },
    relatedServices: [
      ["/services/retaining-walls", "Retaining Walls"],
      ["/services/turf-installation", "Turf Installation"],
      ["/services/garden-planting", "Garden Planting"],
    ],
  },
  {
    slug: "garden-lighting-turf-planter",
    title: "Instant Turf & Feature Planter with Garden Lighting",
    categories: ["Turf", "Hard Landscaping", "Garden Transformations"],
    summary: "Fresh instant turf framed by a stained sleeper planter, shaped red-mulch beds, a white-pebble stepping-stone path and low-voltage garden lighting that brings the yard to life after dark.",
    challenge: "A tired front yard: patchy lawn, scattered pavers, an ageing river-pebble strip and declining shrubs. The established roses and the rock feature were worth keeping; the rest needed a new lawn, defined garden edges, planting and a finish that would look as good at night as it does during the day.",
    scope: [
      "Old lawn, loose pavers and river pebbles removed",
      "Instant turf supply and laying",
      "Stained timber sleeper planter walls",
      "Shaped garden beds with red mulch and white-pebble edging",
      "White-pebble stepping-stone path to the front door",
      "Feature tree and seasonal flower planting, existing roses and rock feature retained",
      "Low-voltage garden lighting along paths and beds",
    ],
    approach: "The old surfaces came out first, then the beds were framed with stained sleeper walls and shaped around the roses and rock feature the owners wanted to keep. Contrasting red mulch and white pebbles were layered around new feature planting, with a stepping-stone path set through the pebbles to the entrance. Warm low-voltage lights were set into the pebble borders so the path and beds stay defined after sunset.",
    outcome: "A finished front yard with real presence — crisp lawn, a clear path to the door and defined beds by day, and a warm, welcoming glow along the path by night.",
    completed: "August 2026",
    hero: "proj-litpath-1",
    gallery: [
      { img: "proj-litpath-1", alt: "Lit pebble path with exposed-aggregate stepping pads and garden lighting at dusk" },
      { img: "proj-litpath-2", alt: "Fresh instant turf and stained sleeper planter with garden lighting in the evening" },
    ],
    /* Two angles of the same frontage, each with its own comparison. The
       first pair doubles as the project's before/after on the hub and
       /before-and-after pages. */
    comparisons: [
      {
        label: "Overall front garden",
        before: { img: "proj-litpath-before-1", alt: "Before: patchy front lawn with scattered pavers and established rose bushes in front of the house" },
        after: { img: "proj-litpath-after-1", alt: "After: fresh turf, shaped red-mulch beds, new planting, a white-pebble stepping-stone path and the existing rock feature" },
      },
      {
        label: "Entrance path",
        before: { img: "proj-litpath-before-2", alt: "Before: side view of the frontage with tired lawn, an ageing river-pebble strip and declining shrubs" },
        after: { img: "proj-litpath-after-2", alt: "After: raised lawn edge, illuminated stepping stones, white-pebble detailing, red mulch and feature planting" },
      },
    ],
    before: { img: "proj-litpath-before-1", alt: "Before: patchy front lawn with scattered pavers and established rose bushes" },
    after: { img: "proj-litpath-after-1", alt: "After: fresh turf, red-mulch beds, a white-pebble stepping-stone path and the rock feature" },
    relatedServices: [
      ["/services/turf-installation", "Turf Installation"],
      ["/services/hard-landscaping", "Hard Landscaping"],
      ["/services/garden-planting", "Garden Planting"],
    ],
  },
  {
    slug: "front-garden-bed-refresh",
    title: "Front Garden Bed Refresh — Pebbles, Mulch & Planting",
    categories: ["Garden Transformations"],
    summary: "A tired pebble bed beside the front entrance reshaped with curved edging, contrasting mulch and stone, and compact new planting around the existing tree.",
    challenge: "The small garden bed beside the driveway had become untidy, with ageing pebbles, sparse plants and no clear shape. The owners wanted a cleaner entrance while keeping the established tree and access to the existing services.",
    scope: [
      "Cleared the ageing pebble surface and untidy growth",
      "Reshaped the bed with curved garden edging",
      "Added a white-pebble feature through the centre",
      "Installed fresh dark mulch through the planting areas",
      "Added compact shrubs and seasonal flowering plants",
      "Retained the established tree and kept the services accessible",
    ],
    approach: "The new layout follows the existing shape of the bed. A curved white-pebble strip breaks up the dark mulch and gives the garden a clear line towards the entrance. Smaller plants were arranged around the tree and service points so the bed stays practical as it grows.",
    outcome: "A clean, defined entrance garden with stronger contrast, fresh planting and a layout that works around the existing property.",
    completed: "July 2026",
    hero: "proj-bedrefresh-after-1",
    gallery: [
      { img: "proj-bedrefresh-before-1", alt: "Before: narrow front garden bed with ageing mixed pebbles and sparse planting beside the driveway" },
      { img: "proj-bedrefresh-after-1", alt: "After: reshaped bed with curved edging, a central white-pebble feature, dark mulch, compact shrubs and flowering plants around the existing tree" },
    ],
    before: { img: "proj-bedrefresh-before-1", alt: "Before: narrow front garden bed with ageing mixed pebbles, sparse planting and no clear structure" },
    after: { img: "proj-bedrefresh-after-1", alt: "After: reshaped bed with curved edging, a central white-pebble feature, dark mulch, compact shrubs and flowering plants" },
    relatedServices: [
      ["/services/garden-planting", "Garden Planting"],
      ["/services/plants-garden-beds-mulch", "Plants, Garden Beds & Mulch"],
    ],
  },
  {
    slug: "synthetic-turf-front-lawn",
    title: "Synthetic Turf Front Lawn",
    categories: ["Turf"],
    summary: "A dense, always-green synthetic lawn installed with clean timber edging and pebble borders — zero mowing, full kerb appeal.",
    challenge: "The owners wanted a lawn that stays green year-round without watering or weekend mowing, finished neatly against the existing established garden.",
    scope: [
      "Old surface removal and base preparation",
      "Compacted base with proper drainage",
      "Quality synthetic turf supply and installation",
      "Timber edging and river-pebble border",
      "Power brushing and final grooming",
    ],
    approach: "The finish of a synthetic lawn is decided by the base, so the ground was excavated, compacted and levelled before the turf went down. Clean timber edging separates the lawn from the pebble border, and a final power brush lifts the pile for a dense, natural look.",
    outcome: "A lush, perfectly even lawn that looks freshly mown every day of the year — with no watering, no mowing and no brown patches.",
    completed: "June 2026",
    hero: "proj-synthetic-1",
    gallery: [
      { img: "proj-synthetic-1", alt: "Dense synthetic turf lawn with timber edging and river-pebble border beside an established garden" },
      { img: "proj-synthetic-2", alt: "Close view of the finished synthetic lawn showing an even, natural-looking pile" },
    ],
    before: { img: "proj-synthetic-before-1", alt: "Before: overgrown, patchy garden area around an established tree beside a timber path" },
    after: { img: "proj-synthetic-after-1", alt: "After: synthetic turf framed by white pebbles, flowers and timber edging, with the established tree and timber path retained" },
    relatedServices: [
      ["/services/synthetic-turf-installation", "Synthetic Turf Installation"],
      ["/services/turf-installation", "Turf Installation"],
      ["/services/garden-care", "Garden Care"],
    ],
  },
  {
    slug: "stained-sleeper-raised-garden",
    title: "Stained Sleeper Raised Garden & Instant Turf",
    categories: ["Retaining Walls", "Turf"],
    summary: "A dark-stained sleeper retaining wall carving a level lawn out of a corner block, finished with pebble borders and flowering colour.",
    challenge: "A sloping corner frontage that needed to be levelled and framed so the new lawn would hold its shape — and look sharp from both streets.",
    scope: [
      "Stained timber sleeper retaining wall with galvanised posts",
      "Soil supply and levelling behind the wall",
      "Instant turf supply and laying",
      "Pebble border and seasonal flower planting",
    ],
    approach: "The retaining wall was built to follow the corner block's two street frontages, stained dark to match the home's palette, then backfilled and levelled for turf. A pebble strip along the wall top keeps the lawn edge crisp and the flowers visible from the street.",
    outcome: "A level, defined front lawn with real street presence from every angle — and a wall built to keep it that way.",
    completed: "August 2026",
    hero: "proj-sleeperbed-1",
    gallery: [
      { img: "proj-sleeperbed-1", alt: "Dark-stained sleeper retaining wall with fresh instant turf and flowering border on a corner block" },
      { img: "proj-sleeperbed-2", alt: "Finished raised garden showing the stained sleeper wall, pebble strip and new lawn" },
    ],
    before: { img: "proj-sleeperbed-before-1", alt: "Before: sloping corner frontage with ageing lawn, pebble beds and tired shrubs" },
    after: { img: "proj-sleeperbed-after-1", alt: "After: level lawn held by a dark-stained timber sleeper retaining wall with galvanised posts, white-pebble trim, flowers and red mulch" },
    relatedServices: [
      ["/services/retaining-walls", "Retaining Walls"],
      ["/services/turf-installation", "Turf Installation"],
      ["/services/mulching", "Mulching"],
    ],
  },
  {
    slug: "natural-turf-installation",
    title: "Natural Turf Installation",
    categories: ["Turf", "Garden Transformations"],
    summary: "A bare, debris-strewn front yard cleared back to soil, levelled and laid with natural turf — an even, clean lawn running the full width of the street frontage.",
    challenge: "The whole front garden had been stripped back to bare ground: an open stretch of uneven dirt with timber offcuts and broken pavers left across it, between the house, the paling fence and the painted picket fence along the street.",
    scope: [
      "Site clearing and debris removal",
      "Ground preparation, raking and levelling",
      "Natural turf supply and laying",
      "Turf cut and fitted to the fence lines and path edges",
      "Watering in after installation",
    ],
    approach: "The ground was cleared, raked and levelled before any turf arrived, because natural turf creates an immediate, living lawn but its long-term success depends on proper ground preparation and early care. A level, well-prepared soil base helps the turf maintain even contact with the ground and establish healthy roots. The slabs were then laid tight against one another and cut in around the existing picket and paling fences, so the seams close up as the lawn knits together.",
    outcome: "An even, clean lawn across the whole frontage, running right up to the fence lines with no gaps or bare edges. Once installed, the lawn needs consistent watering and limited foot traffic while it settles — the sprinkler was already running the next morning.",
    completed: "June 2026",
    hero: "proj-naturalturf-after",
    gallery: [
      { img: "proj-naturalturf-before", alt: "Before: the front garden stripped back to bare, uneven soil with timber offcuts left across it" },
      { img: "proj-naturalturf-progress-1", alt: "During installation: natural turf slabs laid up to the edge of the raked and levelled soil" },
      { img: "proj-naturalturf-progress-2", alt: "During installation: turf slabs butted tightly together across the prepared front garden" },
      { img: "proj-naturalturf-after", alt: "After: an even natural turf lawn covering the full front garden up to the picket fence" },
    ],
    before: { img: "proj-naturalturf-before", alt: "Before: bare, uneven soil across the front garden" },
    after: { img: "proj-naturalturf-after", alt: "After: an even natural turf lawn across the full front garden" },
    relatedServices: [
      ["/services/natural-turf-installation", "Natural Turf"],
      ["/services/turf-preparation-levelling-drainage", "Turf Preparation & Levelling"],
      ["/services/turf-installation", "Turf Installation"],
    ],
  },
  {
    slug: "backyard-natural-turf-installation",
    title: "Backyard Natural Turf Installation",
    categories: ["Turf", "Garden Transformations"],
    summary: "A bare, weed-covered backyard prepared and finished with a broad natural lawn, creating a cleaner and more usable space for the family.",
    challenge: "The backyard was mostly uneven soil and scattered weeds, leaving very little comfortable space for playing or spending time outside. The owners wanted a simple, practical lawn that made proper use of the available area.",
    scope: [
      "Cleared the weeds and unwanted growth",
      "Prepared and levelled the ground",
      "Supplied and laid natural turf",
      "Cut the turf neatly around the existing edges and play area",
      "Watered the lawn in and provided establishment advice",
    ],
    approach: "The ground was cleared and levelled first so the turf could sit evenly across the yard. The turf was laid in straight, tight runs and fitted around the existing boundaries and play equipment.",
    outcome: "A wide, even backyard lawn that gives the family a clean and useful outdoor space.",
    completed: "September 2026",
    hero: "proj-backyardturf-after-1",
    gallery: [
      { img: "proj-backyardturf-before-1", alt: "Before: large backyard of bare, uneven soil and weeds between a brick wall and the rear fence" },
      { img: "proj-backyardturf-after-1", alt: "After: broad natural lawn fitted around the backyard boundaries and the play equipment" },
    ],
    before: { img: "proj-backyardturf-before-1", alt: "Before: bare, uneven soil and weeds across the backyard" },
    after: { img: "proj-backyardturf-after-1", alt: "After: broad natural lawn fitted around the existing boundaries and play equipment" },
    relatedServices: [
      ["/services/natural-turf-installation", "Natural Turf"],
      ["/services/turf-preparation-levelling-drainage", "Turf Preparation & Levelling"],
      ["/services/turf-installation", "Turf Installation"],
    ],
  },
];
