/* =====================================================================
   Central service-page content. Every page gets genuinely distinct,
   trade-specific content — no invented prices, certifications,
   guarantees, counts or partnerships. Images are the site's real
   project photos. Fields the template tolerates as optional:
   whoFor, problems, options, process, prepDrainage, resiCom,
   maintenance, faqs, gallery, beforeAfter.
   ===================================================================== */

const P = {
  planterAfter: "proj-planter-after-1",
  planterBefore: "proj-planter-before-1",
  planterProgress: "proj-planter-progress-1",
  planterNight: "proj-planter-after-night",
  litpath: "proj-litpath-1",
  litpath2: "proj-litpath-2",
  synthetic: "proj-synthetic-1",
  synthetic2: "proj-synthetic-2",
  sleeper: "proj-sleeperbed-1",
  sleeper2: "proj-sleeperbed-2",
  turfCard: "service-natural-turf-solutions",
  pavingCard: "service-paving-and-stepping-stones",
  wallsCard: "service-retaining-walls",
  softCard: "service-soft-landscaping",
  designCard: "service-garden-design",
  hero: "hero-landscaping-northwest-melbourne",
  sideGarden: "project-turf-stepping-stones",
  bannerYard: "project-garden-path",
};

const PLANTER_BA = {
  before: { img: P.planterBefore, alt: "Before: weed-covered mound in front of a new build" },
  after: { img: P.planterAfter, alt: "After: raised sleeper planter with fresh turf, pebbles and flowers" },
  note: "A genuine before and after from our front-garden planter project — see the full case study on our Projects page.",
  link: "/projects/front-garden-planter-transformation",
};

module.exports = {
  primary: [
    /* ================= 1. NATURAL TURF ================= */
    {
      slug: "natural-turf-installation",
      name: "Natural Turf Supply & Installation",
      short: "Natural Turf",
      tagline: "Fresh, hard-wearing natural lawns supplied and laid to suit your soil, sun and lifestyle.",
      image: P.planterAfter,
      intro: "Nothing beats real grass underfoot. We supply and lay quality natural turf over properly prepared, graded and drained ground, so your new lawn takes root quickly and stands up to Melbourne summers, kids and pets.",
      whoFor: "Ideal for family backyards that get real use, front lawns that carry the home's street appeal, and new builds starting from bare soil. If your block gets reasonable sun and you don't mind mowing, natural turf gives the best feel and looks of any surface.",
      problems: [
        "Bare or muddy ground on a new build handover",
        "An old lawn full of weeds, bare patches or invasive grasses",
        "Lawns that flood or stay soggy after rain",
        "Ground too bumpy or sloped to mow properly",
        "Council nature strips that need finishing",
      ],
      included: [
        "Help choosing the right variety for your aspect and use",
        "Site clearing, old lawn removal and weed treatment",
        "Soil preparation, grading and levelling",
        "Quality instant turf, supplied fresh and laid promptly",
        "Rolling, edge trimming and watering-in",
        "Simple establishment care instructions",
      ],
      options: [
        ["Soft-leaf buffalo", "Shade-tolerant with a plush feel — the family-lawn favourite for most Melbourne blocks."],
        ["Couch varieties", "Fine-leafed and hard-wearing in full sun; recovers fast from heavy traffic."],
        ["Kikuyu", "Vigorous, budget-friendly and quick to repair itself — best where there's room for it to run."],
        ["Tall fescue", "Cool-season option that holds colour through winter in shaded, cooler spots."],
      ],
      process: [
        "On-site measure and variety advice",
        "Clear and treat the old surface",
        "Spread and level quality topsoil with correct falls",
        "Lay turf with staggered joints, rolled for soil contact",
        "Water-in and hand over care instructions",
      ],
      prepDrainage: "A lawn is only as good as what's underneath it. We grade the base so water sheds away from the house, add gypsum or sandy loam where Melbourne's clay soils need it, and sort out soggy spots with drainage before the turf goes down — not after it dies.",
      resiCom: "For homes we handle everything from a small front lawn to a full backyard. For commercial sites, builders and body corporates we lay larger areas to programme, coordinate with other trades, and can quote supply-and-lay across multiple properties.",
      faqs: [
        ["When is the best time to lay natural turf?", "Turf can be laid almost year-round in Melbourne. Autumn and spring establish fastest; summer laying works with disciplined watering, and winter simply takes a little longer to knit down."],
        ["How long until I can walk on a new lawn?", "Keep traffic off for around two to three weeks while the roots take hold, then introduce normal use gradually. We'll give you specific guidance for your variety and season."],
        ["How much should I water new turf?", "Daily watering for the first couple of weeks is typical, tapering off as the roots establish. We leave you simple instructions matched to the season."],
        ["Can you remove my old lawn first?", "Yes — old turf removal, weed treatment and disposal are part of the job when needed, so you get a clean start."],
      ],
      gallery: [
        { img: P.planterAfter, alt: "Fresh natural turf laid inside a raised sleeper planter" },
        { img: P.sleeper2, alt: "New natural lawn behind a stained sleeper retaining wall" },
        { img: P.litpath2, alt: "Instant turf and planter beds with garden lighting at dusk" },
      ],
      beforeAfter: PLANTER_BA,
      related: ["synthetic-turf-installation", "turf-preparation-levelling-drainage", "turf-repair-patching", "lawn-mowing"],
    },

    /* ================= 2. SYNTHETIC TURF ================= */
    {
      slug: "synthetic-turf-installation",
      name: "Synthetic Turf Installation",
      short: "Synthetic Turf",
      tagline: "Low-maintenance synthetic lawns that stay green all year — installed on a base built to last.",
      image: P.synthetic,
      intro: "For shaded courtyards, high-traffic areas, rentals, or anyone done with mowing, quality synthetic turf is a genuinely good answer. Installed properly — compacted base, correct drainage, secured edges — it looks sharp year-round with almost no upkeep.",
      whoFor: "Perfect for heavily shaded yards where real grass struggles, small courtyards and side strips that are awkward to mow, pet runs, and busy households that want a green outlook without weekend maintenance.",
      problems: [
        "Grass that refuses to grow in heavy shade",
        "Mud tracked inside from thin, patchy lawn",
        "Watering costs and restrictions killing the lawn each summer",
        "Strata or rental properties that need a tidy, permanent finish",
        "Play areas that turn to dust or mud with use",
      ],
      included: [
        "Excavation and removal of the old surface",
        "Compacted crushed-rock base with correct falls",
        "Weed membrane where conditions call for it",
        "Quality synthetic turf, seamed and secured",
        "Sand infill and power brushing for an even, upright pile",
        "Clean edges against paths, decks and garden beds",
      ],
      options: [
        ["Pile height and density", "From putting-green short to plush 40mm family lawn — we'll show you samples and be straight about the trade-offs."],
        ["Natural multi-tone blends", "Modern turfs mix green tones with a brown thatch layer so the lawn reads natural, not plastic."],
        ["Pet-friendly configurations", "Permeable backing and infill choices that drain quickly and rinse clean."],
      ],
      process: [
        "Measure, sample selection and fixed quote",
        "Excavate and cart away the old surface",
        "Build and compact the crushed-rock base",
        "Lay, seam, trim and secure the turf",
        "Infill, power brush and final tidy",
      ],
      prepDrainage: "The difference between synthetic turf that looks premium and turf that looks fake is nearly all in the base. We compact in layers, set falls so water moves through and away, and never lay over soft ground that will settle into hollows later.",
      resiCom: "At home, synthetic suits courtyards, pool surrounds and play spaces. Commercially, we install for childcare centres, display suites, office courtyards and body corporates where an always-presentable, low-water surface earns its keep.",
      faqs: [
        ["How long does synthetic turf last?", "Quality turf, properly installed, typically gives many years of service depending on traffic and sun exposure. The base preparation is what protects that lifespan — it's where we don't cut corners."],
        ["Is synthetic turf safe for dogs?", "Yes — we install pet-suitable turf with drainage that lets you hose it clean. It's a popular choice for dog runs and side yards."],
        ["Does it get hot in summer?", "Synthetic surfaces do run warmer than natural grass on very hot days. Lighter-toned blends and a quick hose-down help; we'll talk honestly about whether it suits your space."],
        ["Can it go over concrete?", "Often, yes — with the right drainage and padding approach. We'll assess the slab and falls on-site before recommending it."],
      ],
      gallery: [
        { img: P.synthetic, alt: "Dense synthetic lawn with timber edging and pebble border" },
        { img: P.synthetic2, alt: "Close view of a finished synthetic lawn's natural-looking pile" },
        { img: P.sideGarden, alt: "Synthetic turf side garden with stepping stones and climbing flowers" },
      ],
      related: ["natural-turf-installation", "turf-preparation-levelling-drainage", "hard-landscaping", "garden-care"],
    },

    /* ================= 3. TURF PREP / LEVELLING / DRAINAGE ================= */
    {
      slug: "turf-preparation-levelling-drainage",
      name: "Turf Preparation, Levelling & Drainage",
      short: "Prep & Drainage",
      tagline: "The groundwork that decides whether a lawn thrives or fails — done properly, before any turf goes down.",
      image: P.planterProgress,
      intro: "Most lawn failures are ground failures. Poor levels, compacted clay and trapped water kill more Melbourne lawns than any pest or drought. We prepare, level and drain ground properly — for lawns we lay, and for owners planning to lay their own.",
      whoFor: "For anyone whose yard floods, holds puddles, slopes awkwardly or sits as builder's fill — and for those who want the ground professionally prepared before laying turf themselves.",
      problems: [
        "Water pooling on the lawn days after rain",
        "Compacted clay or builder's rubble under thin topsoil",
        "Uneven ground that scalps when mowed",
        "Runoff heading toward the house instead of away",
        "Soft, boggy areas that never firm up",
      ],
      included: [
        "Site assessment of levels, soil and drainage behaviour",
        "Excavation, filling and machine or hand grading",
        "Quality topsoil supply, spread to even depth",
        "Correct falls away from buildings and paths",
        "Ag-pipe, drainage gravel and pit installation where needed",
        "Gypsum and soil conditioning for clay ground",
      ],
      options: [
        ["Surface grading", "Reshaping the ground itself so water sheds naturally — the first and cheapest fix."],
        ["Sub-surface ag drains", "Slotted pipe in gravel trenches for ground that stays wet from below."],
        ["Drainage pits and connections", "Collecting hard-surface runoff and moving it to legal discharge points."],
      ],
      process: [
        "Walk the site after considering where water actually goes",
        "Set levels and falls with laser or string lines",
        "Excavate, fill and grade to the plan",
        "Install drainage where grading alone won't solve it",
        "Finish with topsoil ready for turf",
      ],
      prepDrainage: "This service IS the preparation and drainage — the part of every good lawn you never see. We'd rather tell you your yard needs $500 of grading than sell you turf that will drown in the first wet winter.",
      resiCom: "Residentially, this is the fix for boggy backyards and new-build moonscapes. Commercially, we prepare larger areas to level and drainage specifications ready for turf, and remediate sites where previous landscaping has failed.",
      faqs: [
        ["Do I need drainage, or just levelling?", "Often grading alone solves it — water wants to run downhill. We only recommend sub-surface drainage when the ground genuinely needs it, and we'll show you why on-site."],
        ["Can you prepare the ground and let me lay the turf?", "Absolutely. Preparation-only jobs are common — we hand over a levelled, drained, turf-ready surface and you take it from there."],
        ["What do you do about builder's rubble?", "We excavate what shouldn't be there, cart it away, and replace it with soil a lawn can actually root into."],
      ],
      gallery: [
        { img: P.planterProgress, alt: "Levelled quality topsoil inside a new sleeper planter, ready for turf" },
        { img: P.planterBefore, alt: "Unprepared ground before works: weeds, uneven fill and exposed lines" },
        { img: P.planterAfter, alt: "The same garden finished with turf after proper preparation" },
      ],
      beforeAfter: PLANTER_BA,
      related: ["natural-turf-installation", "synthetic-turf-installation", "retaining-walls", "irrigation-repairs"],
    },

    /* ================= 4. RETAINING WALLS ================= */
    {
      slug: "retaining-walls",
      name: "Retaining Walls",
      short: "Retaining Walls",
      tagline: "Structural walls that hold back slopes, frame gardens and carve out usable, level yard.",
      image: P.sleeper,
      intro: "A retaining wall does real structural work, so it has to be built right. We set posts to correct depth, use materials matched to the load, and put drainage behind every wall so water pushes through it, not against it.",
      whoFor: "For sloping blocks that waste half their space, garden beds that spill onto paths, new builds needing boundary retention, and anyone replacing a leaning or rotted old wall before it fails completely.",
      problems: [
        "Sloped yards with no flat, usable space",
        "Old timber walls rotting, leaning or bulging",
        "Soil washing over paths and driveways after rain",
        "Garden beds with no defined edge or structure",
        "Height transitions between neighbouring properties",
      ],
      included: [
        "Site assessment, levels and set-out",
        "Engineering and permit guidance where wall height requires it",
        "Excavation and footings to suit the load",
        "Wall construction in your chosen material",
        "Ag-drain, gravel backfill and geo-fabric behind the wall",
        "Backfill, compaction and a clean finished site",
      ],
      options: [
        ["Treated pine sleepers", "The cost-effective workhorse — neat, strong and stainable, with galvanised steel posts."],
        ["Hardwood sleepers", "Denser timber and a richer look for feature walls and planters."],
        ["Concrete sleepers", "The set-and-forget choice: termite-proof, rot-proof, in plenty of finishes."],
        ["Block and stone", "Masonry walls for curves, seating height and premium street appeal."],
      ],
      process: [
        "Measure, discuss materials and confirm any engineering needs",
        "Excavate and set posts or footings to depth",
        "Build the wall true to line and level",
        "Install drainage and backfill in compacted layers",
        "Finish the surrounds — soil, turf or pebbles as designed",
      ],
      prepDrainage: "Water pressure is what kills retaining walls. Every wall we build gets ag-pipe at the base, free-draining gravel backfill and fabric separation — so winter rain drains through instead of building up behind the timber.",
      resiCom: "At home: planter walls, terraced slopes and boundary retention like our documented front-garden planter project. Commercially: subdivision boundary walls, carpark edges and staged construction alongside other trades. We'll flag when a wall's height or surcharge needs an engineer's sign-off.",
      faqs: [
        ["Do I need a permit for my retaining wall?", "In Victoria, walls above certain heights or supporting loads generally need engineering and may need a permit. We'll tell you up front if your wall crosses that line and guide the process."],
        ["Which material lasts longest?", "Concrete sleepers and masonry outlast everything. Good treated pine still gives excellent service for its price — the drainage behind the wall matters as much as the material."],
        ["Can you replace just the rotten sleepers?", "Sometimes — if posts are sound. We'll assess honestly; patching a failing wall can cost more long-term than rebuilding it properly."],
      ],
      gallery: [
        { img: P.sleeper, alt: "Dark-stained sleeper retaining wall with galvanised posts on a corner block" },
        { img: P.planterProgress, alt: "Treated-pine planter wall under construction with fresh topsoil" },
        { img: P.sleeper2, alt: "Finished raised garden with stained wall, pebble strip and new lawn" },
      ],
      beforeAfter: PLANTER_BA,
      related: ["hard-landscaping", "turf-preparation-levelling-drainage", "paving", "plants-garden-beds-mulch"],
    },

    /* ================= 5. PAVING ================= */
    {
      slug: "paving",
      name: "Paving",
      short: "Paving",
      tagline: "Patios, paths and entertaining areas laid dead level on a compacted base — built to stay that way.",
      image: P.pavingCard,
      intro: "Good paving is all in the base you don't see. We excavate, compact and screed properly so your patio or path stays flat and true for years — no rocking pavers, no puddles, no weeds pushing through open joints.",
      whoFor: "For outdoor entertaining areas that need a solid, level floor; side paths that turn to mud each winter; front entries that should make a first impression; and pool surrounds that need safe, well-drained surfaces.",
      problems: [
        "Rocking, sunken or lifting pavers from poor bases",
        "Water pooling against the house after rain",
        "Muddy side access that never dries out",
        "Cracked old concrete dragging down the whole yard",
        "Entertaining areas too uneven for a table and chairs",
      ],
      included: [
        "Excavation and removal of the old surface",
        "Compacted road-base foundation, screeded bedding sand",
        "Paver supply and laying to pattern",
        "Cutting for neat edges, curves and penetrations",
        "Edge restraints to lock the field in place",
        "Joint filling and full site clean-up",
      ],
      options: [
        ["Concrete pavers", "Huge range of sizes and colours; excellent value with modern large-format looks."],
        ["Bluestone", "Melbourne's classic — dense, durable and always looks the part."],
        ["Porcelain", "Ultra-low maintenance, stain-resistant, precise edges for contemporary designs."],
        ["Clay pavers", "Warm, colourfast tones that suit period homes and garden paths."],
      ],
      process: [
        "Measure, discuss materials and set levels",
        "Excavate to depth and compact the sub-grade",
        "Build the road-base layer in compacted lifts",
        "Screed bedding sand and lay to string lines",
        "Cut edges, secure restraints, fill joints and clean down",
      ],
      prepDrainage: "Every paved area we build falls gently away from the house — enough to shed water, never enough to feel on a table. Where paving meets lawn or beds, we set edges so mowing stays easy and water has somewhere to go.",
      resiCom: "Home jobs run from a side path to a full alfresco floor. For commercial and body-corporate sites we handle larger format work, accessibility gradients and staged installs that keep access open during works.",
      faqs: [
        ["Paving or concrete — which should I choose?", "Pavers win on looks, repairability (lift and relay a section, not saw-cut a slab) and drainage flexibility. Concrete can suit driveways and utility zones. We'll give you a straight comparison for your job."],
        ["Will weeds grow between my pavers?", "With a compacted base, tight joints and quality joint sand, weed growth is minimal — the odd wind-blown seed wipes off the surface rather than rooting from below."],
        ["Can you match my existing paving?", "Often yes — or we'll suggest a deliberate contrast that looks intentional instead of a near-miss."],
      ],
      gallery: [
        { img: P.pavingCard, alt: "Level paved area laid to pattern" },
        { img: P.litpath, alt: "Exposed-aggregate pads set in a lit pebble path" },
        { img: P.bannerYard, alt: "Front yard with curved paved path, retaining wall and garden beds" },
      ],
      related: ["stepping-stone-paths", "hard-landscaping", "retaining-walls", "natural-turf-installation"],
    },

    /* ================= 6. STEPPING STONE PATHS ================= */
    {
      slug: "stepping-stone-paths",
      name: "Stepping-Stone Paths",
      short: "Stepping Stones",
      tagline: "Practical, beautiful paths through lawns and gardens — set level, spaced right, built to walk on.",
      image: P.litpath,
      intro: "A stepping-stone path does what a solid path can't: it keeps the softness of lawn or pebbles while giving you a clean, dry line to walk. Set at the right spacing and flush with the surface, it's as practical as it is good-looking.",
      whoFor: "For side gardens and lawn crossings that wear a dirt track; garden journeys you want to feel intentional; and spaces where a full paved path would look too hard and heavy.",
      problems: [
        "Worn dirt tracks across the lawn",
        "Wet feet and mud on the walk to the clothesline or shed",
        "Gardens with no way to walk through and enjoy them",
        "Paths that feel like an afterthought to the garden design",
      ],
      included: [
        "Layout on-site so spacing suits a natural stride",
        "Excavation and compacted bedding for each stone",
        "Stones set flush and level with the surrounds",
        "Lawn, pebble or planted infill between stones",
        "Optional low-voltage path lighting",
      ],
      options: [
        ["Concrete pads", "Crisp, uniform, budget-friendly — including exposed-aggregate finishes like our lit path project."],
        ["Natural stone steppers", "Organic shapes and colour variation for garden-style paths."],
        ["Large-format porcelain", "Contemporary lines for modern courtyards."],
        ["Pebble or groundcover infill", "White pebble borders, river stones or creeping plants between stones."],
      ],
      process: [
        "Walk the route and lay stones out loose to test stride",
        "Cut in and prepare a compacted bed for each stone",
        "Set stones flush and level, checked as a run",
        "Finish the infill — turf, pebbles or planting",
      ],
      prepDrainage: "Each stone is bedded on compacted material — not soil — so they don't rock or sink. In pebble paths we contain the field with edging and let water drain straight through, as in our garden-lighting path project.",
      resiCom: "Most stepping-stone work is residential, but the same approach suits display suites, cafés and childcare gardens where a soft path needs to stay safe and level under daily traffic.",
      faqs: [
        ["How far apart should stepping stones be?", "Around 60–65cm centre-to-centre suits a natural adult stride. We always lay stones out loose first and have you walk them before anything is dug in."],
        ["Will the stones sink into the lawn?", "Not when bedded properly. Each stone sits on compacted bedding, flush with the surface — mower-friendly and stable underfoot."],
        ["Can you light the path?", "Yes — low-voltage lighting along a path is an affordable upgrade that transforms how the garden feels at night."],
      ],
      gallery: [
        { img: P.litpath, alt: "Lit stepping-stone path with white pebble borders at dusk" },
        { img: P.sideGarden, alt: "Stepping stones through a synthetic turf side garden" },
        { img: P.litpath2, alt: "Evening view of a finished path, planter and new lawn" },
      ],
      related: ["paving", "hard-landscaping", "plants-garden-beds-mulch", "natural-turf-installation"],
    },

    /* ================= 7. HARD LANDSCAPING ================= */
    {
      slug: "hard-landscaping",
      name: "Hard Landscaping",
      short: "Hard Landscaping",
      tagline: "The structural work that shapes a yard — edges, surfaces, walls and levels, built once and built right.",
      image: P.bannerYard,
      intro: "Hard landscaping is the skeleton of a good outdoor space: the paths, edges, walls and surfaces everything else hangs off. We build it level, drained and durable, so the soft planting on top has something worth sitting on.",
      whoFor: "For complete yard builds on new homes, structural makeovers of tired blocks, and any project where several elements — walls, paving, edging, drainage — need to work as one system rather than separate trades' afterthoughts.",
      problems: [
        "New-build blocks handed over as bare dirt",
        "Yards with no structure — lawn bleeding into beds into paths",
        "Levels that make half the block unusable",
        "Old landscaping failing in stages: edges first, then paving, then walls",
      ],
      included: [
        "Site planning across levels, drainage and access",
        "Retaining walls and terracing",
        "Paving, paths and stepping stones",
        "Garden edging in timber, steel or masonry",
        "Demolition and removal of old surfaces",
        "Drainage integrated into the build, not bolted on",
      ],
      options: [
        ["Timber structure", "Sleeper walls, edging and planters — warm, strong, cost-effective."],
        ["Steel edging", "Crisp curves and straight lines that keep lawn and pebbles exactly where they belong."],
        ["Masonry and stone", "Block walls and stone features where permanence and polish matter."],
        ["Mixed-material builds", "Most of our projects combine timber, steel, stone and pebbles into one coherent design."],
      ],
      process: [
        "Walk the site and agree the plan and levels",
        "Demolition, excavation and ground preparation",
        "Structural work first: walls, then surfaces, then edges",
        "Drainage placed as the levels are built",
        "Soft finishes last — soil, turf, pebbles, plants",
      ],
      prepDrainage: "Building order matters: structure first, drainage with it, surfaces after. Because one team builds the whole system, the levels match, the water has somewhere to go, and there's a single person accountable for the finish.",
      resiCom: "Residential projects run from a structured front yard to a complete backyard build. Commercially we deliver the same scope for developers, builders and body corporates — built to programme and coordinated with other trades on site.",
      faqs: [
        ["Can you do the whole yard, or just one part?", "Both. We're happy quoting a single wall or path — and equally set up to deliver the entire structural stage of a landscape design."],
        ["Do I need a landscape designer first?", "Not always. For most residential jobs we can plan the layout with you on-site. For complex builds we'll work from your designer's drawings, or recommend our garden design service."],
        ["How disruptive is the work?", "There's honest mess in the middle of any structural build. We keep access safe, the site tidy each day, and give you a realistic timeline before we start."],
      ],
      gallery: [
        { img: P.bannerYard, alt: "Structured front yard: retaining wall, paved path, beds and lawn working together" },
        { img: P.sleeper, alt: "Stained sleeper retaining wall shaping a corner block" },
        { img: P.litpath, alt: "Path, pebbles, planter and lighting built as one system" },
      ],
      related: ["retaining-walls", "paving", "stepping-stone-paths", "soft-landscaping"],
    },

    /* ================= 8. SOFT LANDSCAPING ================= */
    {
      slug: "soft-landscaping",
      name: "Soft Landscaping",
      short: "Soft Landscaping",
      tagline: "Garden beds, planting and mulch that turn built structure into a living garden.",
      image: P.softCard,
      intro: "Soft landscaping is what turns a bare block into a garden. We build up good soil, choose plants that suit the spot and your appetite for maintenance, and finish with clean edges and quality mulch so beds look sharp and stay that way.",
      whoFor: "For finished builds that still feel bare; established gardens that have lost their shape; and anyone who wants genuine greenery without signing up for hours of weekly upkeep.",
      problems: [
        "Yards that are 'finished' but feel empty and hard",
        "Beds full of weeds, dead plants and tired mulch",
        "Plants that keep dying because they never suited the spot",
        "Gardens that demand more weekend time than they give back",
      ],
      included: [
        "Garden bed shaping and soil improvement",
        "Plant selection matched to aspect, soil and lifestyle",
        "Supply and planting of trees, shrubs and groundcovers",
        "Quality mulch, compost and feature pebbles",
        "Timber, steel or masonry edging",
        "Establishment watering and care guidance",
      ],
      options: [
        ["Native and water-wise palettes", "Kangaroo paw, grasses, grevilleas — colour and habitat with minimal thirst."],
        ["Contemporary structure", "Clipped forms, feature trees and layered greens for modern facades."],
        ["Cottage and colour", "Seasonal flowering beds like the pebble-edged planters in our recent projects."],
        ["Low-maintenance mixes", "Densely planted beds that shade out weeds and largely look after themselves."],
      ],
      process: [
        "Assess soil, sun and drainage bed by bed",
        "Shape beds and improve the soil properly",
        "Set out plants in pots first, adjust, then plant",
        "Mulch to depth with clean, defined edges",
        "Water in and hand over simple care notes",
      ],
      prepDrainage: "Plants fail in Melbourne clay when water sits at their roots. We improve soil with compost and gypsum, mound beds where drainage is marginal, and choose species that match the ground they're going into — not fight it.",
      resiCom: "Home gardens from a single front bed to a full replant. For commercial and body-corporate landscapes, we plant for durability and low upkeep, matched to a maintenance schedule we can also provide.",
      faqs: [
        ["Which plants survive Melbourne's west?", "Wind-hardy, clay-tolerant and water-wise species — many natives and Mediterranean plants thrive here. We pick to your specific block, not a generic list."],
        ["When is the best time to plant?", "Autumn is Melbourne's planting sweet spot; spring is close behind. We plant year-round with variety choices and establishment care matched to the season."],
        ["How do I keep maintenance low?", "Right plant, right place, good mulch, and density that crowds out weeds. Design choices — not effort — are what make low-maintenance gardens."],
      ],
      gallery: [
        { img: P.softCard, alt: "Mulched garden bed with layered planting" },
        { img: P.planterNight, alt: "Raised planter bed with seasonal flowers and fresh turf at night" },
        { img: P.bannerYard, alt: "Native-style beds with mulch and feature planting around a lawn" },
      ],
      related: ["plants-garden-beds-mulch", "garden-design", "garden-care", "hard-landscaping"],
    },

    /* ================= 9. GARDEN DESIGN ================= */
    {
      slug: "garden-design",
      name: "Garden Design",
      short: "Garden Design",
      tagline: "A clear, costed plan for your outdoor space — designed by the people who will actually build it.",
      image: P.designCard,
      intro: "A good design saves money by getting decisions right before anyone lifts a shovel. We map how your space should flow — lawn, paving, beds, screening, lighting — and hand you a plan you can build in one hit or stage over time.",
      whoFor: "For new builds starting from bare dirt, renovations where the outside should match the inside, and owners who have ideas but want them resolved into something buildable and costed before committing.",
      problems: [
        "A blank block and no idea where to start",
        "Pinterest folders that don't add up to one coherent garden",
        "Quotes that vary wildly because the scope was never defined",
        "Beautiful drawings from studios that no one can afford to build",
      ],
      included: [
        "On-site consultation and measure-up",
        "Concept layout covering levels, flow and zones",
        "Plant and materials palette selection",
        "Practical costing aligned to your budget",
        "Staged build options where funds need spreading",
        "A plan our own crew can price and build immediately",
      ],
      options: [
        ["Layout concept", "The essentials resolved: zones, circulation, levels and surfaces."],
        ["Planting design", "A planting plan with species, quantities and placement."],
        ["Full design-and-build", "One accountable team from first sketch to final clean-up."],
      ],
      process: [
        "Site visit: how you live, what you want, what the block allows",
        "Concept layout and materials direction",
        "Review together and refine",
        "Costing and staging plan",
        "Build when you're ready — with the same team",
      ],
      prepDrainage: "Design is where drainage problems get solved cheaply. We design levels, falls and drainage runs into the plan from day one, because moving water on paper costs nothing compared to moving it after the paving is down.",
      resiCom: "Most design work is residential, from courtyards to full blocks. For developers and commercial clients we design durable, low-maintenance landscapes that survive real-world use and fit maintenance budgets.",
      faqs: [
        ["Why design with a landscaper instead of a design studio?", "Because we build what we draw, our plans are grounded in real costs and buildability. No features you'll never afford; no details that fall apart on site."],
        ["Can I build the design in stages?", "Yes — staging is one of the main reasons to have a plan. Structure first, surfaces second, planting last, each stage complete in itself."],
        ["What do I need before the first meeting?", "Just your ideas and honest budget range. Photos of gardens you like help; we'll bring the practicality."],
      ],
      gallery: [
        { img: P.designCard, alt: "Garden design concept drawing" },
        { img: P.bannerYard, alt: "A designed front yard: wall, path, beds and lawn resolved as one composition" },
        { img: P.hero, alt: "Completed front-garden design with stepping stones, rocks and layered planting" },
      ],
      related: ["hard-landscaping", "soft-landscaping", "retaining-walls", "plants-garden-beds-mulch"],
    },

    /* ================= 10. PLANTS / BEDS / MULCH ================= */
    {
      slug: "plants-garden-beds-mulch",
      name: "Plants, Garden Beds & Mulch",
      short: "Plants & Mulch",
      tagline: "New beds built properly, the right plants for the spot, and mulch that keeps it all healthy.",
      image: P.planterNight,
      intro: "This is the fastest visual upgrade a garden can get: well-shaped beds, healthy soil, plants chosen for the position, and a generous mulch finish. Small scope, big difference — done in days, enjoyed for years.",
      whoFor: "For owners who want defined, planted beds without a full landscape project; refreshes before selling or renting; and gardens where the bones are fine but the beds have gone tired.",
      problems: [
        "Shapeless beds merging into the lawn",
        "Bare soil growing weeds instead of plants",
        "Old mulch gone grey, thin and patchy",
        "Impulse-bought plants dying in the wrong spots",
      ],
      included: [
        "Bed shaping, weeding and soil improvement",
        "Edging to hold the line between bed and lawn",
        "Plant supply and installation",
        "Mulch supplied and spread to proper depth",
        "Feature pebbles and rocks where the design calls for them",
      ],
      options: [
        ["Organic mulches", "Pine bark, euci-mulch and composted blends that feed the soil as they break down."],
        ["Decorative pebbles", "White, river and toned stone finishes like our project planters' crisp pebble borders."],
        ["Coloured mulches", "Red and black mulches for high-contrast beds that photograph beautifully."],
      ],
      process: [
        "Assess each bed's sun, soil and purpose",
        "Clear weeds and improve the soil",
        "Edge, plant and set feature stones",
        "Mulch to depth and water everything in",
      ],
      prepDrainage: "Beds get the same respect as lawns: improved soil, mounding where clay drains slowly, and mulch kept clear of stems so moisture helps plants instead of rotting them.",
      resiCom: "Perfect small-scope residential work — a weekend-sized transformation done in a day or two. For commercial sites, scheduled mulch top-ups and bed refreshes keep street appeal consistent year-round.",
      faqs: [
        ["How deep should mulch be?", "Around 75mm settles to an effective layer — enough to suppress weeds and hold moisture without smothering plants. Thin 'sprinkle' mulching is largely cosmetic."],
        ["How often does mulch need topping up?", "Organic mulches typically want a refresh every year or two as they break down into the soil — which is exactly what they're supposed to do."],
        ["Can you just do one bed?", "Yes. Single-bed makeovers are a genuinely worthwhile job — no project is too small to do properly."],
      ],
      gallery: [
        { img: P.planterNight, alt: "Raised bed with flowers, pebble border and fresh mulch at night" },
        { img: P.softCard, alt: "Freshly mulched bed with layered shrubs" },
        { img: P.sleeper2, alt: "Pebble-edged planting strip along a sleeper wall" },
      ],
      related: ["soft-landscaping", "garden-care", "mulching", "garden-planting"],
    },
  ],

  secondary: [
    /* ================= TIMBER & DECKING ================= */
    {
      slug: "timber-decking",
      name: "Timber & Decking",
      short: "Timber & Decking",
      tagline: "Decks, sleeper work and timber structures built square, level and made to last outdoors.",
      image: P.sleeper,
      intro: "Timber brings warmth to an outdoor space that stone and concrete can't — but only when it's built properly. We construct decks, sleeper retaining and planter boxes, timber edging and screens with the right footings, fixings and finishes for Melbourne conditions.",
      included: [
        "Timber decking construction and repairs",
        "Sleeper retaining walls and raised planter boxes",
        "Timber garden edging and borders",
        "Privacy screens and feature battens",
        "Staining, oiling and finishing",
      ],
      faqs: [
        ["What timber do you recommend for decking?", "It depends on budget and look — treated pine is economical and reliable, hardwoods like merbau or spotted gum wear beautifully. We'll talk through the trade-offs on site rather than pushing one answer."],
        ["Do decks need much maintenance?", "A clean and re-oil every year or two keeps timber looking its best. We build so water drains and air circulates, which is most of the battle against rot."],
        ["Can you repair an existing deck?", "Often, yes — replacing boards, refixing loose sections and refinishing. If the subframe has gone, we'll tell you honestly whether repair or rebuild is the better spend."],
      ],
      gallery: [
        { img: P.sleeper, alt: "Raised timber sleeper planter beds with fresh turf" },
        { img: P.sleeper2, alt: "Timber sleeper garden bed with clean pebble edging" },
      ],
      related: ["retaining-walls", "hard-landscaping", "landscaping-features", "garden-design"],
    },

    /* ================= LANDSCAPING FEATURES ================= */
    {
      slug: "landscaping-features",
      name: "Landscaping Features",
      short: "Features",
      tagline: "The custom finishing touches — lighting, water, borders and features — that turn a tidy yard into a standout one.",
      image: P.litpath,
      intro: "Features are what make a landscape feel designed rather than just installed. From garden lighting that makes the space work after dark to water features, defined borders and one-off custom elements, we build the details that finish a yard properly.",
      included: [
        "Water features",
        "Outdoor and garden lighting",
        "Garden borders and edging",
        "Decorative landscape features",
        "Custom outdoor additions built to your brief",
      ],
      faqs: [
        ["Can features be added to an existing garden?", "Yes — most feature work goes into established yards. Lighting, borders and water features can all be retrofitted with minimal disruption."],
        ["Do you handle the electrical side of garden lighting?", "We design and install the landscape side and work in low-voltage systems; anything requiring mains work is done with a licensed electrician."],
        ["I have an idea that isn't listed — can you build it?", "Tell us what you're picturing. If it can be built safely and well, we'll quote it; if we're not the right trade for it, we'll say so."],
      ],
      gallery: [
        { img: P.litpath, alt: "Garden path lit with low-level landscape lighting at dusk" },
        { img: P.litpath2, alt: "Stepping-stone path with garden lighting and border planting" },
      ],
      related: ["garden-design", "timber-decking", "hard-landscaping", "soft-landscaping"],
    },

    /* ================= 11. PROPERTY MAINTENANCE ================= */
    {
      slug: "property-maintenance",
      name: "Property Maintenance",
      short: "Maintenance",
      tagline: "Ongoing care that keeps a property looking the way it did the day it was finished.",
      image: P.hero,
      intro: "Whether it's your home, a rental or a commercial site, regular maintenance protects what the landscaping cost to build. We keep lawns, gardens, hedges and surfaces presentable on a schedule that suits the property.",
      maintenance: {
        oneOff: "One-off tidy-ups suit pre-sale presentation, end-of-lease returns, or simply reclaiming a yard that's got away. We quote the catch-up as a fixed job, and you decide if ongoing care follows.",
        recurring: "Recurring schedules — fortnightly, monthly or seasonal — keep the property permanently presentable and always cost less per visit than repeated catch-ups. One team that knows your property beats juggling separate trades.",
        resi: "Residential care covers mowing, edges, beds, hedges and general tidiness — flexible around what you enjoy doing yourself.",
        com: "Commercial and body-corporate programs cover common areas, street appeal and safety items (sightlines, path edges, trip hazards) with reliable scheduling and one point of contact.",
        custom: "Every property gets a scope built around what it actually needs — tell us the standard you want and how hands-on you want to be, and we'll shape a schedule and fixed pricing to match. Request a custom scope through the quote form or by phone.",
      },
      included: [
        "Lawn mowing and edging",
        "Garden bed weeding and seasonal tidy-ups",
        "Hedge and shrub maintenance",
        "Pruning, green-waste removal and blow-downs",
        "Seasonal tasks: mulch top-ups, feeding, spraying",
      ],
      faqs: [
        ["How often should a property be serviced?", "Most homes sit well on fortnightly mowing in the growing season, monthly gardens care and seasonal extras. Commercial sites usually need tighter schedules. We'll recommend honestly from the property itself."],
        ["Do you take away the green waste?", "Yes — clippings, prunings and weeds leave with us unless you'd rather keep material for compost."],
        ["Can you look after a rental between tenants?", "Yes — one-off returns to presentable condition, or a standing schedule your property manager can rely on."],
      ],
      gallery: [
        { img: P.hero, alt: "A maintained front garden with healthy lawn and tidy beds" },
        { img: P.sleeper2, alt: "Well-kept raised garden with fresh turf and clean pebble edges" },
      ],
      related: ["lawn-mowing", "garden-care", "hedge-trimming-pruning", "weed-control-spraying"],
    },

    /* ================= 12. LAWN MOWING ================= */
    {
      slug: "lawn-mowing",
      name: "Lawn Mowing & Edging",
      short: "Mowing",
      tagline: "Regular, reliable mowing at the right height — with edges that make the whole yard look finished.",
      image: P.planterAfter,
      intro: "A good lawn is made by consistent care. We mow at the correct height for your grass type — scalping a lawn to stretch out visits is how lawns die — edge cleanly along paths and beds, and leave the site tidy every time.",
      maintenance: {
        oneOff: "One-off cuts suit overgrown catch-ups, pre-inspection tidies and holiday cover. Long-grass jobs are quoted honestly for the extra work involved.",
        recurring: "A regular cycle — weekly to fortnightly in season, stretched in winter — is what actually builds a thick, healthy lawn. Consistency beats intensity.",
        resi: "Home services include mowing, edging along all hard surfaces and beds, and clippings removed.",
        com: "Commercial mowing runs to schedule with photo confirmation available, sized from single premises to multi-site rounds.",
        custom: "Tell us your lawn, standard and frequency preferences and we'll set a fixed per-visit price — adjustable by season.",
      },
      included: [
        "Mowing at the correct height for the variety",
        "Edging along paths, driveways, beds and fences",
        "Clippings caught and removed",
        "Blow-down of paths and hard surfaces",
      ],
      faqs: [
        ["How short should my lawn be cut?", "Depends on the grass: buffalo likes to stay taller than couch. Cutting no more than a third of the blade per visit is the golden rule — it's why regular beats occasional."],
        ["Do you bring your own equipment?", "Yes — commercial-grade, maintained and sharp. Blunt blades tear grass and brown the tips."],
        ["Can you rescue an overgrown lawn?", "Almost always. We stage the height down over a couple of visits rather than scalping it in one, then get it onto a healthy cycle."],
      ],
      gallery: [
        { img: P.planterAfter, alt: "Freshly mown lawn with crisp edges inside a sleeper planter" },
        { img: P.hero, alt: "Neat front lawn with defined edges beside garden beds" },
      ],
      related: ["turf-repair-patching", "weed-control-spraying", "garden-care", "property-maintenance"],
    },

    /* ================= 13. GARDEN CARE ================= */
    {
      slug: "garden-care",
      name: "Garden Care",
      short: "Garden Care",
      tagline: "Seasonal care that keeps garden beds healthy, tidy and improving year on year.",
      image: P.softCard,
      intro: "Gardens are living things — they need feeding, pruning, weeding and the occasional hard word. Our garden care keeps beds healthy and presentable through the seasons, so the garden gets better each year instead of slowly going backwards.",
      maintenance: {
        oneOff: "Seasonal blitzes — a spring reset or autumn cut-back — restore order in a single visit and suit owners who enjoy the in-between upkeep themselves.",
        recurring: "Scheduled visits keep on top of weeds before they seed, pruning at the right time per species, and soil improving steadily under mulch.",
        resi: "Home garden care flexes around you: some clients want everything handled, others just the heavy or timing-critical work.",
        com: "For commercial landscapes we maintain planting for presentation and safety, with replacements flagged before gaps appear.",
        custom: "Gardens differ wildly — we scope care per bed and season, and price it as a clear schedule you can adjust.",
      },
      included: [
        "Weeding and bed tidy-ups",
        "Pruning and deadheading at the right time",
        "Soil improvement and feeding",
        "Mulch top-ups",
        "Seasonal planting refreshes",
      ],
      faqs: [
        ["What does a typical garden care visit include?", "Weeding, targeted pruning, deadheading, a general tidy and a check on plant health — with seasonal extras like feeding and mulch when they're due."],
        ["Can you bring a neglected garden back?", "Usually, yes — most 'dead' gardens are just buried and starved. A recovery visit or two, then light regular care, transforms them."],
        ["Do you plant replacements?", "Yes — like-for-like or better-suited species where something has failed, so beds stay full."],
      ],
      gallery: [
        { img: P.softCard, alt: "Healthy, well-tended mulched garden bed" },
        { img: P.planterNight, alt: "Flowering planter bed kept tidy and full" },
      ],
      related: ["plants-garden-beds-mulch", "hedge-trimming-pruning", "weed-control-spraying", "property-maintenance"],
    },

    /* ================= 14. IRRIGATION REPAIRS ================= */
    {
      slug: "irrigation-repairs",
      name: "Irrigation System Repairs",
      short: "Irrigation",
      tagline: "Find the fault, fix it properly, and get water landing where it should again.",
      image: P.turfCard,
      intro: "Broken heads, leaking lines, dead zones and controllers nobody remembers how to program — irrigation problems waste water and quietly kill the lawn and garden they were meant to protect. We find the fault and fix it properly.",
      maintenance: {
        oneOff: "Most irrigation work is a diagnose-and-repair visit: find the fault, fix or replace the failed parts, reset the controller, test coverage.",
        recurring: "Seasonal checks — spring start-up and summer settings — catch small failures before they cost you a lawn in January.",
        resi: "Home systems from simple tap timers to multi-zone pop-ups; we'll also show you how your controller actually works.",
        com: "Commercial systems get documented zone testing and scheduled inspections so landscapes and warranties stay protected.",
        custom: "If your system needs more than repair, we'll say so plainly and quote options rather than billing endless small fixes.",
      },
      included: [
        "Fault-finding across zones, valves and controllers",
        "Replacing broken heads, risers and fittings",
        "Repairing cut or leaking lines",
        "Controller programming and rain-sensor checks",
        "Coverage adjustment so water lands on plants, not paths",
      ],
      faqs: [
        ["My system runs but a zone stays dry — what's wrong?", "Commonly a failed solenoid valve or a cut line. It's a standard diagnosis — usually fixed the same visit."],
        ["Is drip or spray better for garden beds?", "Drip wins for beds: water at the roots, minimal evaporation and no wet foliage. Sprays still suit lawns."],
        ["Can you set my controller for water restrictions?", "Yes — we'll program compliant schedules and show you how to adjust them seasonally."],
      ],
      gallery: [
        { img: P.turfCard, alt: "Healthy irrigated lawn" },
        { img: P.planterAfter, alt: "Fresh turf established with correct watering" },
      ],
      related: ["natural-turf-installation", "turf-repair-patching", "garden-care", "property-maintenance"],
    },

    /* ================= 15. WEED CONTROL ================= */
    {
      slug: "weed-control-spraying",
      name: "Weed Control & Spraying",
      short: "Weed Control",
      tagline: "Targeted weed control that treats the cause — not just this month's crop.",
      image: P.planterBefore,
      intro: "Weeds are a symptom — of thin turf, bare soil or beds without mulch. We knock down the existing problem with targeted spraying and hand removal, then fix the conditions that let weeds take hold in the first place.",
      maintenance: {
        oneOff: "A knockdown treatment before turf, paving, mulching or a sale gets a site clean in one pass — like the weed-covered mound we cleared for our planter project.",
        recurring: "Scheduled seasonal control keeps broadleaf weeds out of lawns and paths clear year-round, timed to growth cycles rather than the calendar.",
        resi: "Home programs target lawn weeds selectively — killing the weed, not the lawn — plus paths, driveways and beds.",
        com: "Commercial grounds get documented, scheduled treatments keeping paths, carparks and garden areas presentable and compliant.",
        custom: "We'll match products and timing to your surfaces, pets and plantings — tell us the situation and we'll scope it honestly.",
      },
      included: [
        "Selective broadleaf control in lawns",
        "Path, paving and gravel treatments",
        "Garden bed weeding and spot treatment",
        "Pre-emergent options where re-infestation is likely",
        "Follow-up visits where a single pass won't hold",
      ],
      faqs: [
        ["Is spraying safe for pets and kids?", "We use registered products per label directions, tell you exact re-entry times, and use non-chemical methods where they're the better tool."],
        ["Why do my weeds keep coming back?", "Because the gap they grow in is still there. Thickening turf, topping up mulch and pre-emergents fix the cause; spraying alone treats the symptom."],
        ["Can you clear a block before landscaping?", "Yes — knockdown clearing before turf or garden construction is one of our most common jobs."],
      ],
      gallery: [
        { img: P.planterBefore, alt: "A weed-covered garden before clearing and treatment" },
        { img: P.planterAfter, alt: "The same garden finished after clearing, treatment and landscaping" },
      ],
      beforeAfter: PLANTER_BA,
      related: ["lawn-mowing", "mulching", "garden-care", "turf-repair-patching"],
    },

    /* ================= 16. HEDGES ================= */
    {
      slug: "hedge-trimming-pruning",
      name: "Hedge Trimming & Pruning",
      short: "Hedges",
      tagline: "Clean, healthy hedges and shrubs — shaped at the right time of year, cleaned up completely.",
      image: P.sideGarden,
      intro: "A sharp hedge lifts a whole property; a butchered one takes years to recover. We trim and prune for shape and plant health — at the right time of year for the species — and take every scrap of green waste with us.",
      maintenance: {
        oneOff: "One-off shapes and reductions restore overgrown hedges and shrubs, staged where a hard cut would stress the plant.",
        recurring: "Regular light trims keep hedges dense, crisp and easy — the difference between maintaining a shape and repeatedly rescuing one.",
        resi: "Home hedge care covers formal hedges, screening runs, topiary and fruit or feature tree pruning within safe reach.",
        com: "Commercial sites get scheduled trims that maintain sightlines, path clearance and presentation without surprise regrowth.",
        custom: "Every species has its season and limits; we'll build a per-hedge schedule so everything is cut when it should be.",
      },
      included: [
        "Formal hedge trimming and shaping",
        "Shrub and small tree pruning",
        "Rejuvenation pruning for the overgrown",
        "Species-correct timing advice",
        "Full green-waste removal",
      ],
      faqs: [
        ["How often should hedges be trimmed?", "Fast growers may want trimming several times over the warm months; slower species once or twice a year. Frequent light trims always beat occasional hard ones."],
        ["Can a badly overgrown hedge be saved?", "Often — many species reshoot from hard pruning if it's staged and timed correctly. Some don't; we'll tell you which you have before cutting."],
        ["Do you remove the clippings?", "Always — the job isn't finished until the site is cleaner than we found it."],
      ],
      gallery: [
        { img: P.sideGarden, alt: "Neatly maintained garden with trained flowering climbers" },
        { img: P.softCard, alt: "Well-shaped shrubs in a mulched bed" },
      ],
      related: ["garden-care", "property-maintenance", "soft-landscaping", "weed-control-spraying"],
    },

    /* ================= 17. TURF REPAIR ================= */
    {
      slug: "turf-repair-patching",
      name: "Turf Repair & Patching",
      short: "Turf Repair",
      tagline: "Bring a tired, patchy lawn back — without paying to replace the whole thing.",
      image: P.turfCard,
      intro: "Dead patches, worn tracks, dog damage, or a lawn that never recovered from summer — often the fix is repair, not replacement. We patch, level and re-establish problem areas so the whole lawn reads as one again.",
      maintenance: {
        oneOff: "Most repairs are one visit: cut out the failed areas, fix what killed them, patch with matching turf and blend the levels.",
        recurring: "Lawns under heavy use benefit from a seasonal check — small repairs each spring cost a fraction of periodic full relays.",
        resi: "Home repairs cover pet damage, play-area wear, shade thinning and post-trade scars from renovations.",
        com: "Commercial turf gets scheduled patching so high-traffic areas never reach the threadbare stage visitors notice.",
        custom: "If a lawn is genuinely past saving we'll say so and quote a proper reinstall instead — no throwing patches at a lost cause.",
      },
      included: [
        "Honest assessment of what's killing the lawn",
        "Removal and replacement of dead sections",
        "Levelling sunken and worn areas",
        "Variety matching so patches blend in",
        "Advice to stop the problem recurring",
      ],
      faqs: [
        ["Patch or replace — how do I know?", "Rule of thumb: if more than half the lawn is failing, replacement usually wins on cost and result. Under that, patching is genuinely effective. We'll assess it straight."],
        ["Will patches match my existing lawn?", "We match variety and blend edges so repairs disappear as they knit in — usually within weeks in the growing season."],
        ["Why does the same spot keep dying?", "There's always a cause: shade, compaction, pet traffic, irrigation gaps or soil problems. We fix the cause with the patch, or the patch just dies on schedule."],
      ],
      gallery: [
        { img: P.turfCard, alt: "Healthy, even lawn after repair" },
        { img: P.planterAfter, alt: "Established lawn in excellent condition" },
      ],
      related: ["natural-turf-installation", "turf-preparation-levelling-drainage", "lawn-mowing", "irrigation-repairs"],
    },
  ],

  /* Pages kept from the earlier set — valid URLs, lighter content. */
  extra: [
    {
      slug: "turf-installation",
      name: "Turf Installation",
      short: "Turf",
      tagline: "Natural and synthetic lawns supplied and installed on properly prepared ground.",
      image: P.turfCard,
      intro: "Our umbrella turf service: whether natural or synthetic suits you better usually comes down to sun, traffic and how much upkeep you want. We'll talk it through on-site and recommend what genuinely fits your yard and budget.",
      included: ["Site clearing and old surface removal", "Soil preparation, grading and levelling", "Natural turf supply and laying", "Synthetic turf installation", "Watering-in and aftercare advice"],
      related: ["natural-turf-installation", "synthetic-turf-installation", "turf-preparation-levelling-drainage", "turf-repair-patching"],
    },
    {
      slug: "garden-planting",
      name: "Garden Planting",
      short: "Planting",
      tagline: "The right plants, in the right spots, planted to establish properly.",
      image: P.bannerYard,
      intro: "Plants fail when they're wrong for the position. We select and plant for your actual conditions — soil, sun, wind and water — so the garden establishes quickly and keeps looking better each season instead of worse.",
      included: ["Plant selection for soil, sun and style", "Natives and exotics suited to Melbourne", "Proper soil preparation and planting", "Layout planned for mature size", "Establishment care advice"],
      related: ["plants-garden-beds-mulch", "soft-landscaping", "garden-care", "mulching"],
    },
    {
      slug: "mulching",
      name: "Mulching",
      short: "Mulch",
      tagline: "Quality mulch, properly laid — better beds, fewer weeds, less watering.",
      image: P.softCard,
      intro: "Mulch is the cheapest improvement a garden can get: it holds moisture, suppresses weeds, feeds the soil as it breaks down and instantly tidies every bed. We supply and spread quality mulch at proper depth, with clean edges.",
      included: ["Supply of organic and decorative mulches", "Bed preparation and weeding first", "Spreading at correct depth", "Clean, defined edges", "Advice on the right mulch per area"],
      related: ["plants-garden-beds-mulch", "soft-landscaping", "garden-care", "weed-control-spraying"],
    },
    {
      slug: "complete-landscape-transformations",
      name: "Complete Landscape Transformations",
      short: "Transformations",
      tagline: "Full outdoor makeovers — turf, paving, walls and gardens under one team.",
      image: P.hero,
      intro: "Some yards need more than one trade. A complete transformation brings turf, paving, retaining walls, beds and planting together under one team and one plan, so each stage is built in the right order and everything lines up at the end.",
      included: ["One plan covering the whole space", "Demolition and site clearing", "Structural work first: walls and surfaces", "Turf, beds and planting to finish", "Staged builds to suit budget"],
      gallery: [
        { img: P.hero, alt: "A complete front-garden transformation with turf, path, rocks and planting" },
        { img: P.bannerYard, alt: "Front yard rebuilt with wall, path, beds and lawn as one design" },
      ],
      beforeAfter: PLANTER_BA,
      related: ["hard-landscaping", "garden-design", "retaining-walls", "natural-turf-installation"],
    },
  ],
};
